---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent 
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= Cloud Tiering 技术常见问题解答
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 云分层服务

以下常见问题解答与Cloud Tiering的工作原理有关。



=== 使用Cloud Tiering服务有哪些优势？

Cloud Tiering可应对数据快速增长带来的挑战、为您提供以下优势：

* 轻松地将数据中心扩展到云、可提供高达50倍的空间
* 存储优化、平均可节省70%的存储空间
* 平均而言、总拥有成本降低30%
* 无需重构应用程序




=== 哪种类型的数据可用于分层到云？

从本质上讲、主存储系统和二级存储系统上被视为非活动的任何数据都是迁移到云的理想目标。在主系统上、此类数据可以包括快照、历史记录和已完成项目。在二级系统上、这包括包含用于灾难恢复和备份的主数据副本的所有卷。



=== 是否可以对NAS卷和SAN卷中的数据进行分层？

可以、您可以将数据从NAS卷分层到公有 云或私有云、例如StorageGRID。在分层通过SAN协议访问的数据时、NetApp建议使用私有云、因为SAN协议比NAS更容易受到连接问题的影响。



=== 非活动数据或不常用数据的定义是什么？如何控制？

冷数据的定义也可以称为："已有一段时间未访问的卷块(元数据除外)"。"时间量"由名为cooling-days的分层策略属性确定。



=== Cloud Tiering是否会在云层中保留我节省的存储效率？

是的、将数据移至云层时、ONTAP 卷级存储效率会得到保留、例如数据压缩、重复数据删除和数据缩减。



=== FabricPool 与云分层之间有何区别？

FabricPool 是ONTAP的分层技术、可以通过ONTAP 命令行界面和System Manager进行自我管理、也可以通过云分层作为服务进行管理。云分层可将FabricPool 转变为一种托管服务、在ONTAP 和云端均采用高级自动化流程、从而提高混合云和多云部署之间分层的可见性和控制力。



=== 分层到云的数据是否可用于灾难恢复或备份/归档？

否由于卷的元数据从不从性能层分层、因此无法直接访问存储在对象存储中的数据。

但是、可以使用Cloud Tiering在二级系统和SnapMirror目标卷(DP卷)上对所有数据(不包括元数据)进行分层、从而降低数据中心占用空间和TCO、从而实现经济高效的备份和灾难恢复。



=== 是否在卷或聚合级别应用Cloud Tiering？

通过将分层策略与每个卷关联、可以在卷级别启用Cloud Tiering。冷数据标识在块级别完成。



=== Cloud Tiering如何确定要分层到云的块？

与卷关联的分层策略是一种机制、用于控制分层块和分层时间。该策略定义数据块的类型(快照、用户数据或两者)以及冷却期。请参见 link:concept-cloud-tiering.html#volume-tiering-policies["卷分层策略"] 了解详细信息。



=== Cloud Tiering是否支持非活动数据报告？

是的、Cloud Tiering在每个聚合上启用非活动数据报告(IDR)。通过此设置，我们可以确定可分层到低成本对象存储的非活动数据量。



=== 从开始运行时起、IDR显示信息需要多长时间？

配置的冷却期过后、IDR将开始显示信息。使用ONTAP 9.7及更早版本时、IDR的冷却期不可调整、为31天。从ONTAP 9.8开始、可以配置最长为183天的IDR冷却期。



== 许可证和成本

以下常见问题解答与使用Cloud Tiering的许可和成本有关。



=== 使用Cloud Tiering的成本是多少？

将冷数据分层到公有 云时：

* 对于按需购买(PAYGO)、基于使用情况的订阅：每GB每月0.05美元。
* 对于年度(BYOL)订阅、基于期限的订阅：从每GB每月0.033美元开始。


将冷数据分层到NetApp StorageGRID 系统(私有云)时、无需任何成本。



=== 是否可以为同一ONTAP 集群同时提供BYOL和PAYGO许可证？

是的。通过Cloud Tiering、您可以使用BYOL许可证、PAYGO订阅或两者的组合。



=== 如果我已达到BYOL容量限制、会发生什么情况？

如果达到BYOL容量限制、则新冷数据分层将停止、而以前分层的所有数据仍可访问。如果您订阅了_Cloud Manager - Deploy & Manage Cloud Data Services_的PAYGO Marketplace、则新的冷数据将继续分层到对象存储、并且每次使用都会产生费用。



=== Cloud Tiering许可证是否包括云提供商的出站费用？

不可以。



=== 内部系统的重新融合是否受云提供商收取的出口成本的影响？

是的。从公有 云进行的所有读取均需支付出站费用。



=== 如何估算我的云费用？Cloud Tiering是否有"假设"模式？

估算云提供商托管数据所需的费用的最佳方法是使用其计算器： https://calculator.aws/#/["AWS"]， https://azure.microsoft.com/en-us/pricing/calculator/["Azure 酒店"] 和 https://cloud.google.com/products/calculator["Google Cloud"]。



=== 云提供商在从对象存储读取/检索数据到内部存储时是否需要额外付费？

是的。检查 https://aws.amazon.com/s3/pricing/["Amazon S3定价"]， https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["块Blob定价"]，和 https://cloud.google.com/storage/pricing["云存储定价"] 数据读取/检索产生的额外定价。



=== 在启用Cloud Tiering之前、如何估算卷节省的空间并获取冷数据报告？

要获得估计值、只需将ONTAP 集群添加到Cloud Manager中、然后通过"分层集群信息板"进行检查即可、该信息板位于"分层"选项卡中。如果禁用了非活动数据报告(IDR)或在足够长的时间内尚未激活、Cloud Tiering将使用70%的行业常数来计算预计节省量。获得IDR数据后、Cloud Tiering会将节省的空间更新为准确的数据。



== ONTAP

以下问题与 ONTAP 相关。



=== Cloud Tiering支持哪些ONTAP 版本？

Cloud Tiering支持ONTAP 9.2及更高版本。



=== 支持哪些类型的 ONTAP 系统？

单节点和高可用性AFF 、FAS 和ONTAP Select 集群支持云分层。

此外、还支持FabricPool 镜像配置中的集群、但分层配置必须使用System Manager或ONTAP 命令行界面完成。



=== 是否可以仅对使用HDD的FAS 系统中的数据进行分层？

可以、从ONTAP 9.8开始、您可以对HDD聚合上托管的卷中的数据进行分层。



=== 是否可以对加入到FAS 节点使用HDD的集群中的AFF 中的数据进行分层？

是的。可以配置Cloud Tiering、以便对任何聚合上托管的卷进行分层。数据分层配置与使用的控制器类型以及集群是否为异构集群无关。



=== Cloud Volumes ONTAP 如何？

如果您使用的是Cloud Volumes ONTAP 系统、则可以在云分层集群信息板中找到这些系统、以便您全面了解混合云基础架构中的数据分层。但是、Cloud Volumes ONTAP 系统是从云分层进行的只读系统。您无法通过云分层在 Cloud Volumes ONTAP 上设置数据分层。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html["您可以在 Cloud Manager 的工作环境中为 Cloud Volumes ONTAP 设置分层"^]。



=== ONTAP 集群还需要满足哪些其他要求？

这取决于冷数据分层的位置。有关更多详细信息、请参见以下链接：

* link:task-tiering-onprem-aws.html#preparing-your-ontap-clusters["将数据分层到Amazon S3"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["将数据分层到Azure Blob存储"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["将数据分层到Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["将数据分层到StorageGRID"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["将数据分层到S3对象存储"]




== 对象存储

以下问题与对象存储有关。



=== 支持哪些对象存储提供程序？

Cloud Tiering支持以下对象存储提供程序：

* Amazon S3
* Microsoft Azure Blob
* Google Cloud 存储
* NetApp StorageGRID
* 与 S3 兼容的对象存储
* IBM云对象存储(FabricPool 配置必须使用System Manager或ONTAP 命令行界面完成)




=== 我是否可以使用自己的存储分段 / 容器？

可以。设置数据分层时，您可以选择添加新的分段 / 容器或选择现有分段 / 容器。



=== 支持哪些地区？

* link:reference-aws-support.html["支持的 AWS 区域"]
* link:reference-azure-support.html["支持的 Azure 区域"]
* link:reference-google-support.html["支持的 Google Cloud 地区"]




=== 支持哪些 S3 存储类？

Cloud Tiering 支持将数据分层到 _Standard_ ， _Standard-Infrequent Access_ ， _One Zone-Infrequent Access_ ， _Intelligent Tierage_ 和 _Glacier 即时检索 _ 存储类。请参见 link:reference-aws-support.html["支持的 S3 存储类"] 有关详细信息：



=== 为什么Cloud Tiering不支持Amazon S3 Glacier Flexible和S3 Glacier Deep Archive？

不支持Amazon S3 Glacier Flexible和S3 Glacier Deep Archive的主要原因是、云分层设计为高性能分层解决方案 、因此数据必须持续可用且可快速访问以供检索。借助S3 Glacier Flexible和S3 Glacier Deep Archive、数据检索可以在几分钟到48小时之间的任意位置进行。



=== 我是否可以将其他与S3兼容的对象存储服务(例如Wasabi)与Cloud Tiering结合使用？

可以、使用ONTAP 9.8及更高版本的集群支持通过分层UI配置与S3兼容的对象存储。 link:task-tiering-onprem-s3-compat.html["请参见此处的详细信息"]。



=== 支持哪些 Azure Blob 访问层？

Cloud Tiering 支持将非活动数据分层到 _hot_ 或 _cool_ 访问层。请参见 link:reference-azure-support.html["支持的 Azure Blob 访问层"] 有关详细信息：



=== Google Cloud Storage 支持哪些存储类？

Cloud Tiering 支持将数据分层到 _Standard_ ， _Nearline_ ， _Coldline_ 和 _Archive_ 存储类。请参见 link:reference-google-support.html["支持的 Google Cloud 存储类"] 有关详细信息：



=== Cloud Tiering 是对整个集群使用一个对象存储还是对每个聚合使用一个对象存储？

整个集群一个对象存储。



=== 是否可以将多个存储分段附加到同一聚合？

为了进行镜像、每个聚合最多可以附加两个分段、其中冷数据会同步分层到两个分段。这些存储分段可以来自不同的提供程序和不同的位置。但是、目前不支持通过Cloud Tiering UI进行配置—可通过System Manager或CLI进行设置。



=== 是否可以将不同的分段附加到同一集群中的不同聚合？

是的。一般最佳实践是将一个存储分段附加到多个聚合。但是、在使用公有 云时、对象存储服务的IOPS上限为、因此必须考虑多个存储分段。但是、目前不支持通过Cloud Tiering UI进行配置—可通过System Manager或CLI进行设置。



=== 将卷从一个集群迁移到另一个集群时、分层数据会发生什么情况？

将卷从一个集群迁移到另一个集群时、所有冷数据都将从云层读取。目标集群上的写入位置取决于是否启用了分层以及源卷和目标卷上使用的分层策略类型。



=== 将卷从同一集群中的一个节点移动到另一个节点时、分层数据会发生什么情况？

如果目标聚合没有附加云层、则会从源聚合的云层读取数据、并将其完全写入目标聚合的本地层。如果目标聚合附加了云层、则会从源聚合的云层中读取数据、然后先将其写入目标聚合的本地层、以便于快速转换。之后、根据所使用的分层策略、它将写入到云层。

从ONTAP 9.6开始、如果目标聚合与源聚合使用相同的云层、则冷数据不会移回本地层。



=== 如何将分层数据恢复到内部？

回写通常在读取时执行、具体取决于分层策略类型。在ONTAP 9.8之前的版本中、可以通过卷移动操作来回写整个卷。9.8之后、分层UI可选择*恢复所有数据*或*恢复活动文件系统*。 link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["了解如何将数据移回性能层"]。



=== 将现有AFF/FAS控制器更换为新控制器时、是否会将分层数据迁移回内部？

否在"机头交换"操作步骤 期间、唯一需要更改的是聚合的所有权。在这种情况下、它将更改为新控制器、而不会发生任何数据移动。



=== 是否可以在灾难恢复期间使用分层数据恢复卷或系统？

否由于卷的元数据始终存储在本地性能层上、因此如果发生灾难且本地层丢失、则元数据也会丢失、无法引用分层数据。



=== 我是否可以使用云提供商的控制台或对象存储探索器查看分层到存储分层的数据？是否可以在不使用ONTAP 的情况下直接使用存储在对象存储中的数据？

否构建并分层到云的对象不包含单个文件、而是包含来自多个文件的多达1、024个4 KB块。卷的元数据始终保留在本地层上。



=== 是否可以将策略应用于对象存储，以便在不分层的情况下移动数据？

是的。您可以启用生命周期管理，以便 Cloud Tiering 在一定天数后将数据从默认存储类 / 访问层过渡到更经济高效的层。

此生命周期规则将应用于 Amazon S3 和 Google Cloud 存储的选定存储分段中的所有对象，以及 Azure Blob 的选定存储帐户中的所有容器。



== 连接器

以下问题与Cloud Manager Connector相关。



=== 什么是连接器？

Connector是在您的云帐户或内部环境中的计算实例上运行的软件、可使Cloud Manager安全地管理云资源。要使用Cloud Tiering服务、您必须部署Connector。



=== 连接器需要安装在何处？

* 将数据分层到 S3 时， Connector 可以驻留在 AWS VPC 中或您的内部环境中。
* 将数据分层到 Blob 存储时， Connector 可以驻留在 Azure vNet 或您的内部。
* 将数据分层到 Google Cloud Storage 时， Connector 必须驻留在 Google Cloud Platform VPC 中。
* 将数据分层到 StorageGRID 或其他 S3 兼容存储提供程序时，连接器必须位于您的内部。




=== 是否可以在内部部署此连接器？

是的。您可以下载Connector软件并将其手动安装在网络中的Linux主机上。 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html["请参见如何在内部安装Connector"]。



=== 在使用Cloud Tiering之前、是否需要云服务提供商的帐户？

是的。您必须先拥有帐户、然后才能定义要使用的对象存储。在VPC或vNet上的云中设置Connector时、还需要在云存储提供商处创建帐户。



=== 如果连接器发生故障、会产生什么影响？

如果发生连接器故障、则只会影响对分层环境的可见性。所有数据均可访问、新识别的冷数据会自动分层到对象存储。



== 分层策略



=== 有哪些可用分层策略？

分层策略有四种：

●None：将所有数据分类为始终处于热状态；防止将卷中的任何数据移动到对象存储。●冷快照(仅限Snapshot)：仅将冷快照块移至对象存储。●冷用户数据和快照(自动)：冷快照块和冷用户数据块都移动到对象存储。●所有用户数据(所有)：将所有数据分类为冷数据；立即将整个卷移动到对象存储。

link:concept-cloud-tiering.html#volume-tiering-policies["详细了解分层策略"]。



=== 我的数据在哪一点被视为冷数据？

由于数据分层是在块级别完成的、因此在数据块在一段时间内未被访问后、该数据块将被视为冷数据、该时间段由分层策略的minimum-cooling-days属性定义。对于ONTAP 9.7及更早版本、适用范围为2-63天、或者从ONTAP 9.8开始、适用范围为2-183天。



=== 在将数据分层到云层之前、数据的默认冷却期是多少？

冷Snapshot策略的默认冷却期为2天、而冷用户数据和快照的默认冷却期为31天。cooling-days参数不适用于所有分层策略。



=== 执行完整备份时、是否从对象存储中检索到所有分层数据？

在完整备份期间、将读取所有冷数据。数据的检索取决于所使用的分层策略。使用全部和冷用户数据和快照策略时、冷数据不会回写到性能层。使用冷快照策略时、只有在备份使用旧快照时、才会检索其冷数据块。



=== 是否可以为每个卷选择分层大小？

否但是、您可以选择哪些卷符合分层条件、要分层的数据类型及其冷却期。这是通过将分层策略与该卷关联来实现的。



=== 所有用户数据策略是否是数据保护卷的唯一选项？

否数据保护(DP)卷可以与三个可用策略中的任何一个相关联。源卷和目标(DP)卷上使用的策略类型决定了数据的写入位置。



=== 将卷的分层策略重置为无会重新融合冷数据还是仅阻止将来的冷数据块移动到云？

重置分层策略时不会发生重新融合、但它会阻止新的冷块移至云层。



=== 将数据分层到云后、是否可以更改分层策略？

是的。更改后的行为取决于新的关联策略。



=== 如果我要确保某些数据不会移动到云、我应该怎么做？

请勿将分层策略与包含该数据的卷相关联。



=== 这些文件的元数据存储在何处？

卷的元数据始终存储在本地的性能层上—它永远不会分层到云。



== 网络和安全性

以下问题与网络连接和安全性有关。



=== 网络连接要求是什么？

* ONTAP 集群通过端口 443 启动与对象存储提供程序的 HTTPS 连接。
+
ONTAP 可在对象存储之间读取和写入数据。对象存储永远不会启动，而只是响应。

* 对于 StorageGRID ， ONTAP 集群会通过用户指定的端口启动与 StorageGRID 的 HTTPS 连接（此端口可在分层设置期间进行配置）。
* Connector 需要通过端口 443 与 ONTAP 集群，对象存储和云分层服务建立出站 HTTPS 连接。


有关详细信息，请参见：

* link:task-tiering-onprem-aws.html["将数据分层到Amazon S3"]
* link:task-tiering-onprem-azure.html["将数据分层到Azure Blob存储"]
* link:task-tiering-onprem-gcp.html["将数据分层到Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html["将数据分层到StorageGRID"]
* link:task-tiering-onprem-s3-compat.html["将数据分层到S3对象存储"]




=== 为了管理存储在云中的冷数据、我可以使用哪些工具进行监控和报告？

除云分层之外、 https://docs.netapp.com/us-en/active-iq-unified-manager/["Active IQ Unified Manager"^] 和 https://docs.netapp.com/us-en/active-iq/index.html["Active IQ 数字顾问"^] 可用于监控和报告。



=== 如果云提供商的网络链路出现故障、会产生什么影响？

如果发生网络故障、本地性能层将保持联机状态、热数据仍可访问。但是、已移至云层的块将无法访问、应用程序在尝试访问该数据时将收到错误消息。恢复连接后、所有数据都可以无缝访问。



=== 是否有网络带宽建议？

底层FabricPool 分层技术读取延迟取决于与云层的连接。尽管分层可在任何带宽上运行、但建议将集群间LIF放置在10 Gbps端口上、以提供足够的性能。对于此连接器、没有任何建议或带宽限制。



=== 用户尝试访问分层数据时是否存在任何延迟？

是的。云层不能提供与本地层相同的延迟、因为延迟取决于连接情况。为了估算对象存储的延迟和吞吐量、Cloud Tiering提供了一个云性能测试(基于ONTAP 对象存储配置程序)、可在连接对象存储后以及设置分层之前使用该测试。



=== 如何保护数据安全？

AES-256-GCM加密在性能层和云层上均保持不变。TLS 1.2加密用于在各层之间移动时对通过线缆传输的数据进行加密、以及对连接器与ONTAP 集群和对象存储之间的通信进行加密。



=== 是否需要在AFF 上安装和配置以太网端口？

是的。必须在以太网端口上配置集群间LIF、该端口位于HA对中的每个节点上、该HA对托管包含您计划分层到云的数据的卷。有关详细信息、请参见计划对数据进行分层的云提供商的要求部分。



=== 需要哪些权限？

* link:task-tiering-onprem-aws.html#preparing-amazon-s3["对于Amazon、需要具有管理S3存储分段的权限"]。
* 对于Azure、除了您需要为Cloud Manager提供的权限之外、不需要任何额外的权限。
* link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["对于Google Cloud、具有存储访问密钥的服务帐户需要具有存储管理员权限"]。
* link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["对于StorageGRID 、需要S3权限"]。
* link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["对于与S3兼容的对象存储、需要S3权限"]。

